name: "Auto deploy"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bumfo/action-deploy@release/v0
      with:
        ref: 'refs/heads/release/snapshot'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
